<?php

namespace App\Modules\Poll\Entities;

use App\Modules\User\Entities\User;
use Illuminate\Database\Eloquent\Model;

class Poll extends Model
{
    const TYPE = [
        '1' => 'Post Now',
        '2' => 'Schedule'
    ];
    protected $fillable = [
        'question',
        'multiple_option_status',
        'type',
        'start_date',
        'expiry_date',
        'show_on_employee',
        'created_by',
        'updated_by'
    ];

    public function user()
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    public function options()
    {
        return $this->hasMany(PollOption::class, 'poll_id');
    }

    public function responses()
    {
        return $this->hasMany(PollResponse::class, 'poll_id');
    }

    public function pollParticipants()
    {
        return $this->hasMany(PollParticipant::class, 'poll_id');
    }

    public function getType()
    {
        return Poll::TYPE[$this->type ?? 1];
    }

    public function getMultipleOptionStatus()
    {
        $list = Self::multipleOptionStatus();
        return $list[$this->multiple_option_status];
    }

    /**
     * Generated By list
     */
    public static function multipleOptionStatus()
    {
        return [
            '10' => 'No',
            '11' => 'Yes'
        ];
    }
}
