<?php

namespace App\Modules\Survey\Entities;

use App\Modules\User\Entities\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class SurveyQuestion extends Model
{

    protected $fillable = [
        'survey_id',
        'question',
        'question_type',
        'option_a',
        'option_b',
        'option_c',
        'option_d',
        'multiple_option_status',
        'description',
        'created_by',
        'updated_by'
    ];

    public function user()
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    public function survey()
    {
        return $this->belongsTo(Survey::class, 'survey_id');
    }

    public function getQuestionType()
    {
        $list = Self::questionType();
        return $list[$this->question_type];
    }

    public static function questionType()
    {
        return [
            '1' => 'Multiple Choice Question',
            '2' => 'True or False',
            '3' => 'Yes or No',
            '4' => 'Open End Typing'
        ];
    }

    public function getMultipleOptionStatus()
    {
        $list = Self::multipleOptionStatus();
        return $list[$this->multiple_option_status];
    }

    /**
     * Generated By list
     */
    public static function multipleOptionStatus()
    {
        return [
            '10' => 'No',
            '11' => 'Yes'
        ];
    }

}
