stages:
  - deploy

deploy_dev:
  stage: deploy
  only:
    - main
  script:
    - echo "Deploying to development server..."
    - cd /var/www/html/demo/demo-hrms
    - git pull origin main
 #   - composer install --no-dev --prefer-dist
 #   - php artisan migrate --force
    - php artisan cache:clear && php artisan config:clear
  tags:
    - dev